services:
  - type: web
    name: youtube-content-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn content_detection.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
